SELECT ID,TITLE,DIRECTOR,GENRE,REALEASE_YEAR,DURATION FROM movies;

INSERT INTO movies (ID,TITLE,DIRECTOR,GENRE,REALEASE_YEAR,DURATION) VALUES (1,"GUARDIANS OF THE GALAXY","JAMES GUNN","SCIENCE FICTION & ACTION",2014,121)